//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP71Demo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WP71Demo.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Construct.
        /// </summary>
        public static string AppTitleString {
            get {
                return ResourceManager.GetString("AppTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the lite version.
        /// </summary>
        public static string lightCheckString {
            get {
                return ResourceManager.GetString("lightCheckString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin.
        /// </summary>
        public static string loginBoxString {
            get {
                return ResourceManager.GetString("loginBoxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message popup!.
        /// </summary>
        public static string MessageBoxString {
            get {
                return ResourceManager.GetString("MessageBoxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Password.
        /// </summary>
        public static string passwdBoxString {
            get {
                return ResourceManager.GetString("passwdBoxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string passwdString {
            get {
                return ResourceManager.GetString("passwdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select for Private Computer.
        /// </summary>
        public static string privateRadioString {
            get {
                return ResourceManager.GetString("privateRadioString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select for Public Computer.
        /// </summary>
        public static string publicRadioString {
            get {
                return ResourceManager.GetString("publicRadioString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Username.
        /// </summary>
        public static string usernameBoxString {
            get {
                return ResourceManager.GetString("usernameBoxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string usernameString {
            get {
                return ResourceManager.GetString("usernameString", resourceCulture);
            }
        }
    }
}
